### PR TITLE
tables is a function in wtf-wikipedia

### PR DESCRIPTION
**Pull request by dmh43**
Tests are still failing here but I figured I'd share this change while I figure out the source of the error.

Thanks!

### CODE REVIEW

**Comment by spencermountain** [comment]
thanks!

**Comment by vsaarinen** [comment]
This change broke dumpster-dive for me when trying to import the Finnish Wikipedia. I receive the following error:
```
TypeError: o.tables is not a function
    at data.sections.forEach.o (/Users/ville/Repos/wikipedia-extractor/node_modules/dumpster-dive/src/worker/_encode.js:44:25)
    at Array.forEach (<anonymous>)
    at Object.encodeData (/Users/ville/Repos/wikipedia-extractor/node_modules/dumpster-dive/src/worker/_encode.js:43:19)
    at parseWiki (/Users/ville/Repos/wikipedia-extractor/node_modules/dumpster-dive/src/worker/02-parseWiki.js:34:19)
    at SundayDriver.each (/Users/ville/Repos/wikipedia-extractor/node_modules/dumpster-dive/src/worker/index.js:26:16)
    at SundayDriver.doChunk (/Users/ville/Repos/wikipedia-extractor/node_modules/sunday-driver/src/index.js:38:8)
    at doit (/Users/ville/Repos/wikipedia-extractor/node_modules/sunday-driver/src/index.js:77:10)
    at SundayDriver.onData (/Users/ville/Repos/wikipedia-extractor/node_modules/sunday-driver/src/index.js:87:3)
    at ReadStream.stream.on (/Users/ville/Repos/wikipedia-extractor/node_modules/sunday-driver/src/02-start.js:15:10)
    at emitOne (events.js:116:13)
```

**Comment by dmh43** [comment]
@vsaarinen can you confirm that you're copy of dumpster-dive is using the latest version of wtf-wikipedia?

**Comment by spencermountain** [comment]
hey, yeah this is likely my bug, will check it out tomorrow. Any chance you can track-down which Finnish article(s) triggers the error?
cheers

**Comment by vsaarinen** [comment]
@dmh43 It's using wtf_wikipedia 4.2.3.

@spencermountain There are a ton (most?) of them, but e.g. https://fi.wikipedia.org/wiki/The_Beast_of_Alice_Cooper, https://fi.wikipedia.org/wiki/Picasa, https://fi.wikipedia.org/wiki/Web_of_Science and so on.

**Comment by vsaarinen** [comment]
Reverting this PR's change fixed everything for me.

**Comment by spencermountain** [comment]
yeah, fixed in `4.3.0`. 👍

**Comment by dmh43** [comment]
Strange, this breaks things for me on English wikipedia. I'll look a bit closer tomorrow :)

**Comment by dmh43** [comment]
@spencermountain when is `tables` expected to be a function? Looking at the wtf-wikipedia codebase it looks like it's always a function, so I'm confused where the change is happening.

**Comment by spencermountain** [comment]
that encode file takes a flat json object, so nothing is going to be a function there. tables etc are functions of the Doc and Section classes.

**Comment by dmh43** [comment]
Ah I see, is the situation different when passing in a `custom` function to dumpster_dive?

**Comment by spencermountain** [comment]
i suppose the output of custom could be anything at all, so maybe encode file should be more clever/defensive. I guess the only limitation is that `custom` outputs an object, what do you think?

**Comment by dmh43** [comment]
Actually it looks like I had misunderstood part of the API. Slight change to README coming soon :)

**Pull request merged**
